services:
    phpfpm:
        image: itkdev/php8.3-fpm:latest
        user: ${COMPOSE_USER:-deploy}
        extra_hosts:
            - "host.docker.internal:host-gateway"
        environment:
            - PHP_XDEBUG_MODE=${PHP_XDEBUG_MODE:-off}
            - PHP_MAX_EXECUTION_TIME=30
            - PHP_MEMORY_LIMIT=256M
        volumes:
            - .:/app
        profiles:
            - dev

    markdownlint:
        image: itkdev/markdownlint
        volumes:
            - .:/md
        profiles:
            - dev

    prettier:
        # Prettier does not (yet, fcf.
        # https://github.com/prettier/prettier/issues/15206) have an official
        # docker image.
        # https://hub.docker.com/r/jauderho/prettier is good candidate (cf. https://hub.docker.com/search?q=prettier&sort=updated_at&order=desc)
        image: jauderho/prettier
        volumes:
            - ./:/work
        profiles:
            - dev

    node:
        image: node:24
        # https://github.com/nodejs/docker-node/blob/main/docs/BestPractices.md#handling-kernel-signals
        # https://docs.docker.com/reference/compose-file/services/#init
        init: true
        working_dir: /app
        volumes:
            - .:/app
        profiles:
            - dev

    symfony:
        # https://hub.docker.com/r/shinsenter/symfony
        image: shinsenter/symfony:latest
        # For some reason it takes a while before composer.json appear in the project root
        # @todo Investigate why
        healthcheck:
            test: ["CMD", "test", "-f", "composer.json"]
            interval: 2s
            timeout: 60s
            retries: 20
        volumes:
            - ./:/app
        profiles:
            - dev
            - app
            - test
        ports:
            - "80"
        environment:
            APP_ENV: dev
            # Needed to run without requiring a cache
            TIDY_FEEDBACK_DEV_MODE: true
            TIDY_FEEDBACK_DEBUG: true
            TIDY_FEEDBACK_DATABASE_URL: pdo-sqlite://localhost//app/app-tidy-feedback.sqlite
            TIDY_FEEDBACK_DEFAULT_LOCALE: en

    playwright:
        # https://playwright.dev/docs/docker
        # This Playwright version should match the one in `package.json`.
        image: mcr.microsoft.com/playwright:v1.53.2-noble
        # https://playwright.dev/docs/docker#recommended-docker-configuration
        init: true
        ipc: host
        cap_add:
            - SYS_ADMIN
        profiles:
            - test
        depends_on:
            - symfony
        volumes:
            - .:/app
            - /tmp/.X11-unix:/tmp/.X11-unix
        working_dir: /app
        ports:
            - "9323:9323"
