#!/usr/bin/env bash
set -o errexit -o errtrace -o noclobber -o nounset -o pipefail
IFS=$'\n\t'

script_dir=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
cd "$script_dir"

execute() {
  drush tidy-feedback:doctrine:schema-update
  shell curl --verbose http://localhost/tidy-feedback/
}

# shellcheck source=/dev/null
source "$script_dir/base"
